### ISSUE TITLE
RSS not working (Error 404)

### ISSUE THREAD

**Issue by mwip** [bbatsov/emacsredux#2]
Thanks for your awesome content!

I would love to follow your updates via RSS. 
However, I found that the [RSS-Link](https://emacsredux.com/feed.xml) is not working. 404...

Please let me know, if you need someone to test it :)

**Comment by bbatsov** [comment]
The actual link is https://emacsredux.com/atom.xml. It predates the blog using Jekyll (that's why I couldn't change it to the one Jekyll uses by default) and the problem stems from the fact I couldn't find an easy way to override the auto-generated feed link.

**Comment by mwip** [comment]
Ok, thanks. I'll close
